# Generated by Django 4.1.1 on 2022-12-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='static/default-user.png', upload_to='patient/'),
        ),
    ]
