# Generated by Django 4.1.1 on 2022-12-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_register_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Patient',
        ),
    ]
