# Generated by Django 4.1.1 on 2022-12-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_register_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
