# Generated by Django 4.1.1 on 2022-12-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
