# Generated by Django 4.1.1 on 2022-12-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='department/')),
            ],
            options={
                'db_table': 'dept_tb',
            },
        ),
    ]
