# Generated by Django 4.1.1 on 2022-12-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
