# Generated by Django 4.1.1 on 2022-12-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0004_alter_department_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_email', models.CharField(max_length=50)),
                ('doctor_contact', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='doctor/')),
                ('username', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_admin.department')),
            ],
            options={
                'db_table': 'doctr_tb',
            },
        ),
    ]
