# Generated by Django 4.1.1 on 2022-12-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0005_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
