# Generated by Django 4.1.1 on 2022-12-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0006_doctor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('pic', models.ImageField(upload_to='staff/')),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'staff_tb',
            },
        ),
    ]
