# Generated by Django 4.1.4 on 2023-01-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_booking_age_booking_gender_booking_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presciption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=20)),
                ('days', models.IntegerField()),
                ('medicine_time', models.CharField(max_length=20)),
                ('intake_time', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.booking')),
            ],
            options={
                'db_table': 'prescription_tb',
            },
        ),
    ]
