# Generated by Django 4.1 on 2023-01-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_patient_password'),
        ('patient', '0003_presciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.patient'),
        ),
    ]
