# Generated by Django 4.1.4 on 2022-12-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0008_consultation'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulting',
            new_name='Consultion',
        ),
    ]
